[tool.poetry]
name = "lessons"
version = "0.1.0"
description = ""
authors = ["Stefan2501 <stef.12@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
